server:
  port: 8087

cowin:
  apiUrl: "http://localhost:8080"

topic:
  user.requests: "user-requests"
  user.districts: "user-districts"
  user.bypincode: "users-by-pincode"
  updated.pincodes: "updated-pincodes"

telegram:
  enabled: true
  bot.username: covid19_vaccine_tracker_bot
  db.path: "/tmp/telegram.db"

jobs:
  cron:
    vaccine.availability: "0 0/5 6-23 * * *"
    district.notifications: "-"
    pincode.reconciliation: "-"
    cowin.api.auth: "-"
    db.cleanup: "0 55 23 * * *"

logging:
  level:
    org.apache.kafka.streams: INFO

users.over45: ""

spring:
  kafka:
    streams:
      application-id: "org.covid19.vaccine-tracker"
      client-id: "org.covid19.vaccine-tracker"
    properties:
      "application.id": "org.covid19.vaccine-tracker"
      "client.id": "org.covid19.vaccine-tracker"
