SET
    SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET
    time_zone = "+00:00";

ALTER TABLE `sessions`
    ADD COLUMN IF NOT EXISTS `cost` VARCHAR(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL AFTER `vaccine`
